remote_theme: jackw01/jackw01.github.io
title: A Better Light Source For Scanning Color Negative Film
description: ' '
hide_first_h1: true
plugins:
  - jekyll-seo-tag
custom_buttons:
  - 1:
    url: https://github.com/jackw01/scanlight
    text: View on GitHub
  - 2:
    url: https://ko-fi.com/jackw01
    text: Support me on Ko-fi
