remote_theme: jackw01/jackw01.github.io
# used by SEO tag
title: A Better Light Source For Scanning Color Negative Film
description: ' '
author:
  name: Jack Whittaker
  url: https://jackw01.github.io
logo: https://jackw01.github.io/logo.png
defaults:
  - scope:
      path: ""
    values:
      image: images/light_assembly_top.jpg
social:
  name: Jack Whittaker
  links:
    - https://github.com/jackw01
    - https://www.linkedin.com/in/jack-whittaker-b35961183/
# end seo
hide_first_h1: true
#title_h1_override: A Better Light Source For Scanning Color Negative Film
plugins:
  - jekyll-seo-tag
nav_items:
  - 1:
    url: index
    text: original article
  - 2:
    url: hw_v2
    text: scanlight v2/v3 info
  - 3:
    url: big
    text: big scanlight info & instructions
custom_buttons:
  - 1:
    url: https://github.com/jackw01/scanlight
    text: View on GitHub
  - 2:
    url: https://ko-fi.com/jackw01/shop
    text: Buy scanlight on Ko-fi
